runtime: python39

handlers:

- url: /.*
  script: auto

entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT main:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "norse-botany-313902-e681a09bd1bc.json"
