data = {
    "id": 7537793,
    "version": 2,
    "account": {
        "id": 29896590,
        "type": "binance_futures_coin",
        "name": "Binance Futures COIN-M",
        "market": "Binance Futures COIN-M",
        "link": "/accounts/29896590",
    },
    "pair": "BTC_BTCUSD_PERP",
    "instant": False,
    "status": {"type": "finished", "title": "Finished"},
    "leverage": {"enabled": True, "type": "isolated", "value": "10.0"},
    "position": {
        "type": "buy",
        "editable": False,
        "units": {"value": "1.0", "editable": False},
        "price": {
            "value": "35717.7",
            "value_without_commission": "35703.4",
            "editable": False,
        },
        "total": {"value": "0.00279973"},
        "order_type": "market",
        "status": {"type": "finished", "title": "Finished"},
    },
    "take_profit": {
        "enabled": True,
        "steps": [
            {
                "id": 26420367,
                "order_type": "market",
                "editable": False,
                "units": {"value": "1.0"},
                "price": {"value": "35757.0", "type": "last", "percent": None},
                "volume": "100.0",
                "total": "0.00279665",
                "trailing": {"enabled": False, "percent": None},
                "status": {"type": "finished", "title": "Finished"},
                "data": {"cancelable": False, "panic_sell_available": False},
                "position": 1,
            }
        ],
    },
    "stop_loss": {"enabled": False},
    "note": "",
    "skip_enter_step": False,
    "data": {
        "editable": False,
        "current_price": {
            "bid": "35672.9",
            "ask": "35673.0",
            "last": "35672.9",
            "day_change_percent": "-5.401",
            "quote_volume": "186574.20024112",
        },
        "target_price_type": "price",
        "base_order_finished": True,
        "missing_funds_to_close": 0,
        "liquidation_price": "32602.3384623",
        "average_enter_price": "35717.7",
        "average_close_price": "35746.0",
        "average_enter_price_without_commission": "35703.4",
        "average_close_price_without_commission": "35760.3",
        "panic_sell_available": False,
        "add_funds_available": False,
        "force_start_available": False,
        "force_process_available": False,
        "cancel_available": False,
        "finished": True,
        "base_position_step_finished": True,
        "created_at": "2021-06-18T23:59:05.014Z",
        "updated_at": "2021-06-18T23:59:05.014Z",
        "closed_at": "2021-06-18T23:59:49.199Z",
        "type": "smart_trade",
    },
    "profit": {
        "volume": "0.000002221104",
        "usd": "0.0794273453712",
        "percent": "0.08",
        "roe": "0.8",
    },
    "margin": {"amount": "9.964166769", "total": "0.00027897"},
    "is_position_not_filled": False,
}
