data = {
    "id": 7516779,
    "version": 2,
    "account": {
        "id": 29896590,
        "type": "binance_futures_coin",
        "name": "Binance Futures COIN-M",
        "market": "Binance Futures COIN-M",
        "link": "/accounts/29896590",
    },
    "pair": "ETH_ETHUSD_PERP",
    "instant": False,
    "status": {"type": "stop_loss_in_progress", "title": "Stop Loss in progress"},
    "leverage": {"enabled": True, "type": "isolated", "value": "10.0"},
    "position": {
        "type": "sell",
        "editable": False,
        "units": {"value": "100.0", "editable": False},
        "price": {
            "value": "2310.02",
            "value_without_commission": "2310.95",
            "editable": False,
        },
        "total": {"value": "0.43289509"},
        "order_type": "market",
        "status": {"type": "finished", "title": "Finished"},
    },
    "take_profit": {"enabled": True, "steps": []},
    "stop_loss": {
        "enabled": True,
        "order_type": "market",
        "editable": False,
        "price": {"value": None},
        "conditional": {
            "price": {"value": "2322.23", "type": "last", "percent": None},
            "trailing": {"enabled": True, "percent": None},
        },
        "timeout": {"enabled": False, "value": None},
        "status": {"type": "finished", "title": "Finished"},
    },
    "note": "",
    "skip_enter_step": False,
    "data": {
        "editable": False,
        "current_price": {
            "bid": "2321.89",
            "ask": "2321.9",
            "last": "2322.47",
            "day_change_percent": "-4.75",
            "quote_volume": "960447.24628549",
        },
        "target_price_type": "price",
        "base_order_finished": True,
        "missing_funds_to_close": 0,
        "liquidation_price": "2554.90212852",
        "average_enter_price": "2310.02",
        "average_close_price": None,
        "average_enter_price_without_commission": "2310.95",
        "average_close_price_without_commission": None,
        "panic_sell_available": True,
        "add_funds_available": False,
        "force_start_available": False,
        "force_process_available": True,
        "cancel_available": True,
        "finished": False,
        "base_position_step_finished": True,
        "created_at": "2021-06-17T18:00:21.841Z",
        "updated_at": "2021-06-17T18:00:21.841Z",
        "type": "smart_cover",
    },
    "profit": {
        "volume": "-0.0020418164",
        "usd": "-4.742057334508000000000077456764501853672",
        "percent": "-0.47",
        "roe": "-4.7",
    },
    "margin": {"amount": "99.853848528", "total": "0.0432264"},
    "is_position_not_filled": False,
}
